# -*- coding: utf-8 -*-
"""Kalkulatoripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFHemKE75LFzXG-WPOHD-XTaRB-kjJiw
"""



import streamlit as st
import math

def hitung_jarak(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Judul aplikasi
st.header("📏 Kalkulator Jarak antara Dua Titik (Koordinat Kartesius)")

st.markdown("Masukkan koordinat titik pertama dan kedua:")

# Input titik pertama
x1 = st.number_input("x1", value=0.0, format="%.2f")
y1 = st.number_input("y1", value=0.0, format="%.2f")

# Input titik kedua
x2 = st.number_input("x2", value=0.0, format="%.2f")
y2 = st.number_input("y2", value=0.0, format="%.2f")

# Tombol untuk menghitung jarak
if st.button("Hitung Jarak"):
    jarak = hitung_jarak(x1, y1, x2, y2)
    st.success(f"Jarak antara titik ({x1}, {y1}) dan ({x2}, {y2}) adalah **{jarak:.2f}** satuan.")
